version: '3.9'
services:
  db:
    image: mysql:8.0.37
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: L34ndr0.$1lv@
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: java-rest-by-erudio
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network
  java-rest-by-erudio:
    image: bambatera/java-rest-by-erudio
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/java-rest-by-erudio?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: L34ndr0.$1lv@
    ports:
      - 80:80
    expose:
      - 80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge