spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/java-rest-by-erudio?useTimezone=true&serverTimezone=UTC&useSSL=false
        username: root
        password: L34ndr0.$1lv@
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        show-sql: false
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQLDialect