spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/java-rest-by-erudio?useTimezone=true&serverTimezone=UTC
        username: root
        password: L34ndr0.$1lv@
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
            show-sql: false