name: Continuous Integration with GitHub Actions

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./
      run: mvn -f ../pom.xml clean package

    - name: Docker Compose Build
      working-directory: ../
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/java-rest-by-erudio:latest ${{ secrets.DOCKER_USERNAME }}/java-rest-by-erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/java-rest-by-erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/java-rest-by-erudio:latest
